# TP06 - Implantation sous SPIN de l'algorithme de Naimi et Trehel
#
# @author Ilyas Toumlilt <toumlilt.ilyas@gmail.com>
#
# @version 1.0
# @package toumlilt/M1/AR

SRC=src

naimi-spin: $(SRC)/naimi.pml
	spin $(SRC)/naimi.pml

naimi-ispin: $(SRC)/naimi.pml
	ispin $(SRC)/naimi.pml

